# **ÖDEV-2**

1-Numpy kütüphanesini import edin.

In [1]:
import numpy as np

2-1'den 5 e kadar (5 dahil) b isimli bir dizi oluşturun.

In [2]:
b = np.array(range(1,6))
b

array([1, 2, 3, 4, 5])

3- 20 adet 0'dan oluşan 4 x 5' lik dizi oluşturun.

In [3]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4- 15 adet 7 sayısından oluşan diziyi 3x5 olarak yazın.

In [4]:
np.full((3,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

5- 10–70 e kadar 5 er artan sayıları yaz.

In [5]:
np.arange(10, 70, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

6- 10–20 arasında 15 aynı uzaklıkta elemanı olan array oluşturun. (linspace metodunu kullanın.)

In [6]:
np.linspace(10, 20, 15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

7- Rastgele sayılardan oluşan diziyi 3x5 boyutunda yazdır.

In [7]:
np.random.randint(100, size = (3, 5))

array([[62, 10, 29, 98, 56],
       [38, 16, 52, 91,  8],
       [30, 60, 71, 99,  3]])

8- 5 elemanlı birim matris oluşturun. eye() metodu kullanın.

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9- 0'dan 24 e kadar array oluştur. Sonra reshape metodu ile 4x6 boyutu olarak yazın.

In [9]:
x = np.array(range(0,24))
x.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

10- 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayın. Minimum ve maksimum değerleri bulun.

In [10]:
y = np.random.random(10)
print(y.max())
print(y.min())

0.7352432579613583
0.04672915622419638


11- 36 sayıdan oluşan rastgele sayılar 6x6' lık array olarak yazdırın.

In [11]:
z = np.random.randint(36, size = (6,6))
z

array([[16, 33, 18, 16, 26, 26],
       [14, 33, 35, 17,  4, 15],
       [34, 27,  8, 18,  2, 31],
       [21,  1, 18, 15, 32, 29],
       [ 3,  1, 29, 15,  5, 27],
       [11,  4,  1, 11,  4, 24]])

12- 5.satırdaki elemanları gösteriniz.

In [12]:
z[4]

array([ 3,  1, 29, 15,  5, 27])

13- 6.satır ve 6.sutundaki elemanları gösteriniz.

In [13]:
print(z[[5], :])
print(z[:, [5]])

[[11  4  1 11  4 24]]
[[26]
 [15]
 [31]
 [29]
 [27]
 [24]]


14-4.sutundaki tüm elemanları çekin.

In [14]:
z[:,[3]]

array([[16],
       [17],
       [18],
       [15],
       [15],
       [11]])

15- For döngüsünü ve flat metodunu kullanarak satır satır elemanları yazdırınız.

In [15]:
for i in range(len(z)):
    print(z[i].flatten())


[16 33 18 16 26 26]
[14 33 35 17  4 15]
[34 27  8 18  2 31]
[21  1 18 15 32 29]
[ 3  1 29 15  5 27]
[11  4  1 11  4 24]


16- 0 ile 1 aralığında bir array oluştur. Bu array değerini 5 ile çarpın.

In [16]:
v = np.random.random(size = 5)
y = v * 5
print(v)
print(y)

[0.35464244 0.44681227 0.9930846  0.4016443  0.46079548]
[1.7732122  2.23406133 4.965423   2.00822149 2.30397738]


16- Satırların toplam değeri nedir?

In [17]:
print(v.sum())
print(y.sum())

2.656979079076755
13.284895395383778


17-Satırların standart sapma değeri nedir?

In [18]:
print(v.std())
print(y.std())

0.23382580265056457
1.1691290132528231


18-Satırların varyans değeri nedir?

In [19]:
print(v.var())
print(y.var())

0.05467450598518077
1.3668626496295198


19- Satırların transpoz değeri nedir?

In [20]:
print(v.transpose())
print(y.transpose())

[0.35464244 0.44681227 0.9930846  0.4016443  0.46079548]
[1.7732122  2.23406133 4.965423   2.00822149 2.30397738]
